# Netlify configuration for VidGrab Pro

[build]
  # Build command
  command = "cd frontend && npm run build"
  
  # Directory to publish (relative to root of repo)
  publish = "frontend/dist"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https: wss:; media-src 'self' blob: data:;"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]  
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]  
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Function timeout
[functions]
  timeout = 30

# Split testing
[context.production.environment]
  VITE_API_URL = "https://vidgrab-pro-api.herokuapp.com/api"
  VITE_ENABLE_ANALYTICS = "true"

[context.deploy-preview.environment]
  VITE_API_URL = "http://localhost:3001/api"  
  VITE_ENABLE_ANALYTICS = "false"

[context.branch-deploy.environment]
  VITE_API_URL = "http://localhost:3001/api"
  VITE_ENABLE_ANALYTICS = "false"