/** @type {import('tailwindcss').Config} */

/*
 * Design tokens live in src/styles/index.css as space-separated RGB triplets and
 * are mapped in here. That is the single source of truth: light and dark values
 * sit next to each other in one place, and no component ever hardcodes a hex.
 *
 * The old config had three colour families (primary blue, success green, warning
 * amber) plus a `hero-pattern` blue-to-purple gradient. Every heading, the logo,
 * and the footer used `from-primary-600 to-purple-600`. That gradient is the most
 * recognisable "generated by AI" signature on the web, and on a downloader site
 * it reads as an ad-farm. One accent now, no gradients.
 */
const token = (name) => `rgb(var(--${name}) / <alpha-value>)`;

export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  // System preference only. A sun/moon toggle is the other cliché and it needs
  // state, storage, and a flash-of-wrong-theme guard to work properly.
  darkMode: 'media',
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: token('surface'),
          raised: token('surface-raised'),
          sunken: token('surface-sunken'),
        },
        line: {
          DEFAULT: token('line'),
          strong: token('line-strong'),
        },
        content: {
          DEFAULT: token('text'),
          muted: token('text-muted'),
          subtle: token('text-subtle'),
        },
        accent: {
          DEFAULT: token('accent'),
          hover: token('accent-hover'),
          fg: token('accent-fg'),
          soft: token('accent-soft'),
          'soft-fg': token('accent-soft-fg'),
        },
        danger: {
          DEFAULT: token('danger'),
          soft: token('danger-soft'),
          'soft-fg': token('danger-soft-fg'),
          fg: token('danger-fg'),
        },
        warn: {
          DEFAULT: token('warn'),
          soft: token('warn-soft'),
          'soft-fg': token('warn-soft-fg'),
        },
      },

      fontFamily: {
        // IBM Plex Sans Arabic carries real Arabic design intent across 300-700,
        // which Inter does not have at all. Latin glyphs come from the same
        // superfamily so mixed Arabic/Latin strings keep one voice.
        sans: ['"IBM Plex Sans Arabic"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },

      // One radius system, documented: inputs and buttons 10px, cards 14px,
      // large containers 20px. Tighter inside, softer outside.
      borderRadius: {
        control: '10px',
        card: '14px',
        panel: '20px',
      },

      // Shadows tinted with the neutral hue instead of pure black.
      boxShadow: {
        raised: '0 1px 2px 0 rgb(24 24 27 / 0.05), 0 1px 3px 0 rgb(24 24 27 / 0.06)',
        lifted: '0 4px 12px -2px rgb(24 24 27 / 0.08), 0 2px 4px -2px rgb(24 24 27 / 0.06)',
        focus: '0 0 0 3px rgb(var(--accent) / 0.25)',
      },

      maxWidth: {
        prose: '65ch',
      },

      keyframes: {
        'rise-in': {
          from: { opacity: '0', transform: 'translate3d(0, 12px, 0)' },
          to: { opacity: '1', transform: 'translate3d(0, 0, 0)' },
        },
        'sweep': {
          from: { transform: 'translate3d(-100%, 0, 0)' },
          to: { transform: 'translate3d(100%, 0, 0)' },
        },
      },
      animation: {
        'rise-in': 'rise-in 0.4s cubic-bezier(0.16, 1, 0.3, 1) both',
        sweep: 'sweep 1.4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
